### ISSUE TITLE
В методе "sumGenre" нарушена логика оператор "else".

### ISSUE THREAD

**Issue by Sapfirka** [boogerman92/TeamProject#1]
> # Описание
> В методе "sumGenre" в операторе else внутри цикла for. Если текущая игра не соответствует входному жанру, код устанавливает sum в 0. В результате метод вернет 0, если первая встреченная игра не соответствует входному жанру, а так же сбросит текущее значение sum, что приведет к неверному результату.
> 
> # Локация дефекта
> 
https://github.com/boogerman92/TeamProject/blob/90e923e9dc955e763d3f56d31e98afd00291dd4e/src/main/java/ru/netology/Player.java#L51
> 
> # Шаги воспроизведения
> 1. Открыть [код программы](https://github.com/boogerman92/TeamProject/blob/Player/src/test/java/ru/netology/PlayerTest.java) в IDEA
> 2. Запустить тест.
> 3. Посмотреть вывод консоли:
> 
> _Ожидаемый результат:_ Process finished with exit code 0
> 
> 
> # Скриншот
> ![image]![image](https://user-images.githubusercontent.com/122283094/225158379-c584d42a-ad27-4c30-ad3a-12585a2d56ce.png))
> 
> # Окружение
> * **Операционная система**  Windows 10 Pro
> * **IDE**  IntelliJ IDEA version: 2022.3.1
> * **Java** OpenJDK11

**Comment by boogerman92** [comment]
Проблема устранена. Код исправлен.
