### ISSUE TITLE
В методе containsGame нарушено начало цикла

### ISSUE THREAD

**Issue by boogerman92** [boogerman92/TeamProject#2]
> # Описание
> Метод проверяет наличие игры в каталоге и возврашает true, если игра есть и false если в каталоге её нет. При добавлении игры в каталог и её выводе, игра не находится. При добавлении трёх игр, находятся только первые две игры.
> 
> # Локация дефекта
> 
https://github.com/boogerman92/TeamProject/blob/90e923e9dc955e763d3f56d31e98afd00291dd4e/src/main/java/ru/netology/GameStore.java#L32
> 
> # Шаги воспроизведения
> 1. Открыть [код программы](https://github.com/boogerman92/TeamProject/blob/GameStore/src/test/java/ru/netology/GameStoreTest.java) в IDEA
> 2. Запустить тест.
> 3. Посмотреть вывод консоли:
> 
> _Ожидаемый результат:_ Process finished with exit code 0
> 
> 
> # Скриншот
> ![BugGameStoreTest](https://user-images.githubusercontent.com/109026336/225254254-5f23c22a-6c6f-4056-b027-0b00a0ca37bc.jpg)

> 
> # Окружение
> * **Операционная система**  Windows 11 Home
> * **IDE**  IntelliJ IDEA version: 2021.3.2
> * **Java** OpenJDK11

**Comment by Sapfirka** [comment]
Метод отредактирован
