### ISSUE TITLE
Некорректный подсчёт сыгранного времени игроком

### ISSUE THREAD

**Issue by boogerman92** [boogerman92/TeamProject#3]
> # Описание
> Методы addPlayTime и getSumPlayedTime работают некорректно. При добавлении зарегистрированному игроку часы игры, программа их не считает, а просто возвращает 0.
> 
> # Локация дефекта
> 
https://github.com/boogerman92/TeamProject/blob/e86f1ea5d297d12faf33dedbf7c6dc205b7cee61/src/main/java/ru/netology/GameStore.java#L46
https://github.com/boogerman92/TeamProject/blob/e86f1ea5d297d12faf33dedbf7c6dc205b7cee61/src/main/java/ru/netology/GameStore.java#L75
> 
> # Шаги воспроизведения
> 1. Открыть [код программы](https://github.com/boogerman92/TeamProject/blob/GameStore/src/test/java/ru/netology/GameStoreTest.java) в IDEA
> 2. Запустить тест.
> 3. Посмотреть вывод консоли:
> 
> _Ожидаемый результат:_ Process finished with exit code 0
> 
> 
> # Скриншот
> ![BugGameStoreTestSum](https://user-images.githubusercontent.com/109026336/225611297-d78f801d-5f05-4c64-b34c-6903e7732a33.jpg)

> 
> # Окружение
> * **Операционная система**  Windows 11 Home
> * **IDE**  IntelliJ IDEA version: 2021.3.2
> * **Java** OpenJDK11

**Comment by Sapfirka** [comment]
add correction at addPlayTime and getSumPlayedTime methods.
