### ISSUE TITLE
Метод  "mostPlayerByGenre" не реализован, выдает только null 

### ISSUE THREAD

**Issue by Sapfirka** [boogerman92/TeamProject#5]
> # Описание
 > В методе "mostPlayerByGenre" не прописан сам метод.
 > # Локация дефекта
 
>https://github.com/boogerman92/TeamProject/blob/08c20b2b4d671382e70d643cbcfa71c00564fb2e/src/main/java/ru/netology/Player.java#L59-L60
 
 > # Шаги воспроизведения
 > 
 > 1. Открыть [код программы](https://github.com/boogerman92/TeamProject/blob/Player/src/test/java/ru/netology/PlayerTest.java) в IDEA
 > 2. Запустить тест.
 > 3. Посмотреть вывод консоли:
 > 
 > _Ожидаемый результат:_ Process finished with exit code 0
 > # Скриншот
 >![image](https://user-images.githubusercontent.com/122283094/225905326-f605a94d-4609-42cf-88d9-efe243118d20.png)

 > # Окружение
 > 
 > * **Операционная система**  Windows 10 Pro
 > * **IDE**  IntelliJ IDEA version: 2022.3.1
 > * **Java** OpenJDK11

**Comment by boogerman92** [comment]
Метод реализован.

**Comment by boogerman92** [comment]
Метод реализован.

**Comment by boogerman92** [comment]
MostPlayedByGenre прописан. Тесты выполняются.
